name: Build and deploy ASP.Net Core app to Azure

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] # ТУТ МАГІЯ 1: Тепер білд запускається і під час Pull Request!
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' 

      - name: Restore
        run: dotnet restore $(find . -name "*.slnx")

      - name: Build
        run: dotnet build $(find . -name "*.slnx") --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test $(find . -name "*.slnx") --configuration Release --no-build

      - name: Publish
        run: |
          PROJ_FILE=$(find . -name "LNUBookShare.Web.csproj" | head -n 1)
          echo "Знайдено проект: $PROJ_FILE"
          dotnet publish "$PROJ_FILE" -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ./publish

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lnu-bookshare-pmi33'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .